/*
 * Copyright 2016 Stormpath, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.stormpath.sdk.application;

import com.stormpath.sdk.api.ApiKey;
import com.stormpath.sdk.resource.Auditable;
import com.stormpath.sdk.resource.Resource;
import com.stormpath.sdk.resource.Saveable;

/**
 * A WebConfiguration resource is used to configure how the {@link Application} owner of {@link WebConfiguration this}
 * resource, to act as server less client.
 *
 * @since 1.2.0
 */
public interface WebConfiguration extends Resource, Saveable, Auditable {

    /**
     * Returns the WebConfiguration's Domain name, this is automatically generated by Stormpath (using the {@link #getDnsLabel() value}
     * and is guaranteed to be unique across all {@link com.stormpath.sdk.tenant.Tenant tenants} in Stormpath.
     *
     * @return the WebConfiguration's Domain name value or {@code null} if one hasn't been generated for {@code this}
     * resource.
     */
    String getDomainName();

    String getDnsLabel();


    void setDnsLabel(String dnsLabel);

    /**
     * Returns the webConfiguration's status. Users won't be able to use the applications' api if the webConfiguration is
     * disabled.
     *
     * @return the webConfiguration's status.
     */
    WebConfigurationStatus getStatus();

    /**
     * Sets the webConfiguration's status. Users won't be able to use the applications' api if the webConfiguration is
     * disabled.
     *
     * @param status the webConfiguration's status.
     */
    void setStatus(WebConfigurationStatus status);

    ApiKey getSigningApiKey();

    void setSigningApiKey(ApiKey apiKey);

    Application getApplication();

    /**
     * Property to configure
     *
     * @return {@link OAuth2Property property}
     */
    OAuth2Property getOAuth2();

    /**
     * @return {@link EnabledProperty property} value of the register control.
     */
    EnabledProperty getRegister();

    /**
     * Property that controls the logic that must exist in order to facilitate self-service verification of newly
     * registered user accounts.
     *
     * @return {@link EnabledProperty property} value of the verifyEmail control.
     */
    EnabledProperty getVerifyEmail();

    /**
     * Property that controls the  logic that must exist in order to facilitate self-service login of user accounts.
     *
     * @return {@link EnabledProperty property} value of the login control.
     */
    EnabledProperty getLogin();

    /**
     * Property that controls the  logic endpoint is used to delete the Authentication Cookies that were set on login.
     * The access and refresh tokens that were issued (and stored in cookies) must also be deleted from the
     * Stormpath REST API.
     *
     * @return {@link EnabledProperty property} value of the logout control.
     */
    EnabledProperty getLogout();

    /**
     * Property that controls the  logic that must exist in order to facilitate self-service login of user accounts.
     *
     * @return {@link EnabledProperty property} value of forgotPa control.
     */
    EnabledProperty getForgotPassword();

    /**
     * Property that controls the  logic that must exist in order to facilitate self-service login of user accounts.
     *
     * @return {@link EnabledProperty property} value of the changePassword control.
     */
    EnabledProperty getChangePassword();

    /**
     * Property that controls the  logic that must exist in order to facilitate self-service idSite of user accounts.
     *
     * @return {@link EnabledProperty property} value of the idSite control.
     */
    EnabledProperty getIdSite();

    /**
     * Property that controls the  logic that must exist in order to facilitate self-service callback of user accounts.
     *
     * @return {@link EnabledProperty property} value of the callback control.
     */
    EnabledProperty getCallback();

    /**
     * Property that controls  the logic that allows the client application to fetch the account object of the currently
     * authenticated user.
     *
     * @return {@link MeProperty property} value of the me control.
     */
    MeProperty getMe();
}
